config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "rooms#index"
  resources :users,only: [:edit, :update]
  resources :rooms,only: [:new,:create,:destroy] do
    resources :messages, only: [:index, :create] #まず、メッセージ送信機能に必要なindexとcreateのルーティングを記述します。
  #メッセージを投稿する際には、どのルームで投稿されたメッセージなのかをパスから判断できるようにしたいので、ルーティングのネストを利用します。
#今回の場合、ネストをすることにより、roomsが親で、messagesが子という親子関係になるので、チャットルームに属しているメッセージという意味になります。
#これによって、メッセージに結びつくルームのidの情報を含んだパスを、受け取れるようになります。
#上記のルーティングを設定した後に、「rails routes」コマンドを実行しましょう。
#URIに注目すると、ネストによって、/rooms/:room_id/messagesとなっています。これはメッセージに紐付いているチャットルームのidという意味です。
#サイドバーのチャットルーム名に、 <%= link_to room.name, room_messages_path(room) %>とリンクを設定します。
# パスにroomを引数とすることで、メッセージと紐付いているチャットルームのidを持たせることができます。
# したがって、チャットルーム名をクリックすると、messagesコントローラーのindexアクションが実行され、チャットルームのページに遷移できます。


end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

belongs_to :user #1つのチャットルームに、メッセージは複数存在します。1人のユーザーは、複数のメッセージを送信できます
belongs_to :room #messagesテーブルに対して、roomsテーブルとusersテーブルは1対多の関係になります。
has_one_attached :image

validates :content, presence: true,unless: :was_attached? #空の場合はDBに保存しないというバリデーションを設定しています。
  def was_attached?
    self.image.attached?
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users,through: :room_users,dependent: :destroy
  has_many :messages, dependent: :destroy #1つのチャットルームに、メッセージは複数存在します。
  #つまり、roomsテーブルに対して、messagesテーブルは、1対多の関係になります。

  validates :name, presence: true #チャットルームを新規作成するにあたって「ルーム名」は必ず必要なので、上記のバリデーションは「ルーム名が存在（presence）している場合のみ作成可（true）」という意味です。
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true #Userモデルに、validates :name, presence: trueを追記します。
  # 「name」カラムに、presence: trueを設けることで、空の場合はDBに保存しないというバリデーションを設定しています。
  # つまり、ユーザー登録時に「name」を空欄にして登録しようとすると、エラーが発生します。       
  has_many :room_users
  has_many :rooms,through: :room_users
  has_many :messages #1人のユーザーは、複数のメッセージを送信できます。つまり、usersテーブルに対して、messagesテーブルは、1対多の関係になります。
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user! #この記述により、ログインしていないユーザーをサインアップの画面に促すことができます。
  before_action :configure_permitted_parameters, if: :devise_controller? #Railsでは、悪意のあるユーザーの入力に対してセキュリティ対策を行わないと保存できない仕組みがあります。
  # 通常のテーブルに保存する際はストロングパラメータを使用しましたが、deviseを使ったモデルの場合は方法が異なります。  
  # application_controllerにbefore_actionを使用しているため、全てのアクションが実行される前に、 before_action :configure_permitted_parameters, if: :devise_controller?が実行されることになります。
  # deviseのコントローラーから呼び出された場合は、configure_permitted_parametersメソッドが呼ばれます。

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
  end #ここでconfigure_permitted_parametersメソッドの定義を行なっています。
  #deviseをインストールすることでdevise_parameter_sanitizerメソッドが使えるようになります。deviseでユーザー登録をする場合に使用でき、「特定のカラムを許容する」メソッドです。
  #今回は「nameカラム」を追加したので、このメソッドを使用し、「name」キーの内容の保存をpermitメソッドで許可しています。





end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    #paramsに含まれているroom_idを代入します。
# 紐解いて説明すると、直前の問題にあった通りルーティングをネストしているため/rooms/:room_id/messagesといったパスになります。
# パスにroom_idが含まれているため、paramsというハッシュオブジェクトの中に、room_idという値が存在しています。そのため、params[:room_id]と記述することでroom_idを取得できます。
    @messages = @room.messages.includes(:user)
    #チャットルームに紐付いている全てのメッセージ（@room.messages）を@messagesと定義します。
# そして、一覧画面で表示するメッセージ情報には、ユーザー情報も紐付いて表示されます。
# この場合、メッセージに紐付くユーザー情報の取得に、メッセージの数と同じ回数のアクセスが必要になるので、N+1問題が発生します。
# その場合は、includesメソッドを使用して、解消しましょう。
# 全てのメッセージ情報に紐づくユーザー情報を、includes(:user)と記述をすることにより、ユーザー情報を1度のアクセスでまとめて取得することができます。
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
    #@room.messages.newでチャットルームに紐づいたメッセージのインスタンスを生成し、message_paramsを引数にして、privateメソッドを呼び出します。
#その値を@messageに代入し、saveメソッドでメッセージの内容をmessagesテーブルに保存します。
    
      redirect_to room_messages_path(@room)
    else
      render :index
    end
    #@message.saveでメッセージの保存に成功した場合、room_messages_path(@room)
#（参加しているチャットルームに投稿したメッセージの一覧画面）にリダイレクトし、失敗した場合、indexアクションが実行され、同じページに戻るという記述をします。
end

private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
    #パラメーターの中に、ログインしているユーザーのidと紐付いている、メッセージの内容(content)を受け取れるように許可します。
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end
  
  
  def new
    @room = Room.new
  end

  def create
    @room = Room.create(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new #うまく行かなかった場合はrenderでrooms/new.html.erbにページを戻しています。
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end
  #どのをチャットルームを削除するのかを特定する場合は、Room.find.params[:id]を使用して、削除したいチャットルームの情報を取得します。
# destroyアクションは、削除するだけなのでビューの表示は必要はありません。
# そのため、インスタンス変数ではなく変数としてroomを定義し、destroyメソッドを使用します。
# destroyメソッドが実行されたら、root（roomsのindex）にリダイレクトする記述をします。


  private
  def room_params
    params.require(:room).permit(:name, user_ids:[])#配列に対して保存を許可したい場合は、キーの名称と関連づけてバリューに「[]」と記述します。
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end #updateアクション内で、保存できた場合とできなかった場合で条件分岐の処理を行います。
   # current_user.updateに成功した場合、root（チャット画面）にリダイレクトします。
   # 失敗した場合、render :editとeditのアクションを指定しているため、editのビューが表示されます。
  end

  private

  def user_params
    params.require(:user).permit(:name,:email)
  end #Userモデルの更新を行うupdateアクションをusersコントローラーに定義しましょう。
  # ストロングパラメーターを使用し、user_paramsを定義します。
  # user_paramsの中でpermitメソッドを使用し、「name」と「email」の編集を許可します。
  # そして、ユーザー情報が格納されているcurrent_userメソッドを使用して、ログインしているユーザーの情報を更新します。

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%=link_to "チャットを終了する", room_path(@room), method: :delete %>
      <%#rails routesを実行すると、削除のパスはroom_pathとなります。
削除するチャットルームを区別するために、定義している@roomを引数にし、room_path(@room)と指定しましょう。
HTTPメソッドのdeleteを指定すると、roomsコントローラーのdestroyアクションが実行されます。%>
    </div>
  </div>
</div>

<div class="messages">
  <%=render partial: 'message',collection: @messages %>
</div>


<%= form_with model: [@room,@message], html:{class: "form"}, local: true do |f| %> <%#今回のコードでは、form_withの引数に@room, @messageの2つを渡している点に注意してください。
これは、messagesのルーティングがroomsにネストされているためです。チャットルームとメッセージとの間には、あるチャットルームに属しているメッセージ、という親子関係があります。
記述したform_withの第1引数@roomには「指定のチャットルームのレコード情報」、第2引数@messageには「Messageモデルのからのインスタンス（Message.new）」をあらかじめセットしておく必要があります。次に、これらの変数をコントローラーのindexアクションで定義しましょう。%> 
  <div class="form-input">
   <%= f.text_field :content, class: 'form-message', placeholder: 'type a message'%>
    <label class="form-image">
      <span class="image-title">画像</span>
      <%= f.file_field :image, class: 'hidden'%>
    </label>
  </div>  
  <%= f.submit '送信', class: 'form-submit' %>
<%end%>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
        <div class="message-user">
          <!--投稿したユーザー名情報を出力する -->
          <%= message.user.name%> <%#メッセージテーブルのuser_idに紐付いているユーザー名をuser.nameとする事で取得%>
        </div>
        <div class="message-date">
          <!--投稿した時刻を出力-->
          <%= l message.created_at%><%#messagesテーブルのcreated_atカラムの情報を取得。下も同じ%>
        </div>
  </div>
  <div class="lower-message">    
        <div class="message-content">
          <!---投稿したメッセージ内容を記述-->
          <%= message.content%>
        </div>
        <%= image_tag message.image.variant(resize:'500x500'), class: 'message-image' if message.image.attached?%>
        <%#このようにif message.image.attached?と記述することで、画像が存在する場合のみimage_tagが読み込まれるようになります。%>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<%#<div class="side_bar>%>
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to edit_user_path(current_user) do %>
      <%= current_user.name %>
    <% end %> <%#「rails routes」コマンドを実行し、どのようなリンク先を指定すれば、該当のアクションが動くのか確認しましょう。%>
              <%#ユーザーの編集機能へのリンクは、以下が該当するのがわかります。%>
  <%#edit_user	GET	/users/:id/edit(.:format)	users#edit %>
  <%#link_toのパスを、ログインしているユーザーの編集をするため 、
edit_user_path(current_user)と指定します。
current_user.nameは、ログインしているユーザー名です。
ユーザー名をクリックすると、usersコントローラーのeditアクションが実行され、編集ページに遷移できます。%>
  
  </div>
  <div class="create-room">
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>

<div class= "rooms">
 <% current_user.rooms.each do |room|%>
  <div class="room">
    <div class="room-name">
      <%= link_to room.name, room_messages_path(room)%> <%#「name」は、roomsテーブルのカラム名%>
    </div>
  </div>
 <% end %>
</div>
<%#/div%%>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">    
  <%= render "side_bar"%>
  </div>

  <div class="chat">
  <%= render "main_chat"%>
  </div>
</div>  

app/views/rooms/index.html.erb
<div class="wrapper">
<div class="side-bar">
<%= render "messages/side_bar"%>
</div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]" > <%#送信されるparamsは {"room[user_ide][]: "選択したユーザーのid"} %>
          <option value="">チャットするユーザーを選択してください</option>
          <% User.all.where.not(id: current_user.id).each do |user|%>
          <option value=<%=user.id%>><%= user.name%></option>
          <%end%>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%=current_user.id %>>
      <%#送信されるparamsは{"room[user_ids][]" => "選択したユーザーのid, 現在ログインしているユーザーのid"} %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'btn'%>
      <%#link_toのパスを、destroy_user_session_pathと指定します。
HTTPメソッドのdeleteを指定すると、ログイン時に使用されるdeviseのsessionsコントローラーのdestroyアクションが実行されます。%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>